In [117]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [118]:
df = pd.read_csv("../../data/placement.csv")
df.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [119]:
df.shape

(200, 2)

In [120]:
X = df[['cgpa']]
y = df['package']

X.head()

   cgpa
0  6.89
1  5.12
2  7.82
3  7.42
4  6.94

In [121]:
y[:4]

0    3.26
1    1.98
2    3.25
3    3.67
Name: package, dtype: float64

In [122]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [123]:
model.coef_, model.intercept_

(array([0.56959129]), np.float64(-0.9856779462557332))

In [124]:
class GDRegressor:

    def __init__(self, learning_rate = 0.01, epochs = 1000):
        self.coef_ = None
        self.intercept_ = None
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.loss_history = []
        
    def fit(self, X_train, y_train):

        self.coef_ = 0
        self.intercept_ = 0

        for i in range(self.epochs):
            y_pred = self.coef_ * X_train.ravel() + self.intercept_
            error = y_train - y_pred
            loss_function = np.mean(error ** 2)
            
            gradient_coef = -2 * np.mean(error * X_train.ravel())
            gradient_intercept  = -2 * np.mean(error)

            self.coef_ -= self.learning_rate * gradient_coef
            self.intercept_ -= self.learning_rate * gradient_intercept

            self.loss_history.append(loss_function)

            if (i + 1) %100 == 0 or i== 0:
                print(f"Epoch {i+1}/{self.epochs} - MSE:{loss_function: .3f} - Coef:{self.coef_: .3f}- Intercept: {self.intercept_: .3f}")


    def predict(self, X_test):

        return self.coef_ * X_test + self.intercept_

In [125]:
X = df['cgpa'].to_numpy()
y = df['package'].to_numpy()

In [126]:
gd = GDRegressor()
gd.fit(X, y)

Epoch 1/1000 - MSE: 9.452 - Coef: 0.432- Intercept:  0.060
Epoch 100/1000 - MSE: 0.130 - Coef: 0.430- Intercept:  0.014
Epoch 200/1000 - MSE: 0.128 - Coef: 0.436- Intercept: -0.030
Epoch 300/1000 - MSE: 0.126 - Coef: 0.442- Intercept: -0.072
Epoch 400/1000 - MSE: 0.124 - Coef: 0.447- Intercept: -0.112
Epoch 500/1000 - MSE: 0.123 - Coef: 0.453- Intercept: -0.150
Epoch 600/1000 - MSE: 0.121 - Coef: 0.458- Intercept: -0.186
Epoch 700/1000 - MSE: 0.120 - Coef: 0.463- Intercept: -0.221
Epoch 800/1000 - MSE: 0.119 - Coef: 0.467- Intercept: -0.255
Epoch 900/1000 - MSE: 0.118 - Coef: 0.472- Intercept: -0.287
Epoch 1000/1000 - MSE: 0.117 - Coef: 0.476- Intercept: -0.317